#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-datanucleus-api-jdo
Version  : 3.2.7
Release  : 1
URL      : https://github.com/datanucleus/datanucleus-api-jdo/archive/datanucleus-api-jdo-3.2.7.tar.gz
Source0  : https://github.com/datanucleus/datanucleus-api-jdo/archive/datanucleus-api-jdo-3.2.7.tar.gz
Source1  : https://repo1.maven.org/maven2/org/datanucleus/datanucleus-api-jdo/3.2.6/datanucleus-api-jdo-3.2.6.jar
Source2  : https://repo1.maven.org/maven2/org/datanucleus/datanucleus-api-jdo/3.2.6/datanucleus-api-jdo-3.2.6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-datanucleus-api-jdo-data = %{version}-%{release}

%description
datanucleus-api-jdo
===================
Support for DataNucleus persistence using the JDO API (JSR0022, JSR0243).

%package data
Summary: data components for the mvn-datanucleus-api-jdo package.
Group: Data

%description data
data components for the mvn-datanucleus-api-jdo package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/datanucleus/datanucleus-api-jdo/3.2.6
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/datanucleus/datanucleus-api-jdo/3.2.6/datanucleus-api-jdo-3.2.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/datanucleus/datanucleus-api-jdo/3.2.6
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/datanucleus/datanucleus-api-jdo/3.2.6/datanucleus-api-jdo-3.2.6.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/datanucleus/datanucleus-api-jdo/3.2.6/datanucleus-api-jdo-3.2.6.jar
/usr/share/java/.m2/repository/org/datanucleus/datanucleus-api-jdo/3.2.6/datanucleus-api-jdo-3.2.6.pom
